trigger:
  branches:
    include:
      - main

pool:
  name: 'Default'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '3.x'
    installationPath: $(Agent.ToolsDirectory)/dotnet

- script: |
   sudo apt update -y
   sudo apt install unzip -y
  displayName: 'Command Line Script'

- task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@1
  displayName: 'Install Terraform latest'

- task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV4@4
  displayName: 'Terraform : init'
  inputs:
    backendServiceArm: 'npstackro-1676009261708 (14f56a24-f129-441e-a95b-0df01d75c3a7)'
    backendAzureRmResourceGroupName: 'rg_agent'
    backendAzureRmStorageAccountName: storageaccountagentshub
    backendAzureRmContainerName: 'agent-container'
    backendAzureRmKey: terraform.tfstate

- task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV4@4
  displayName: 'Terraform : plan'
  inputs:
    command: plan
    environmentServiceNameAzureRM: 'npstackro-1676009261708 (14f56a24-f129-441e-a95b-0df01d75c3a7)'
    backendServiceArm: 'npstackro-1676009261708 (14f56a24-f129-441e-a95b-0df01d75c3a7)'
    backendAzureRmResourceGroupName: 'rg_agent'
    backendAzureRmStorageAccountName: storageaccountagentshub
    backendAzureRmContainerName: 'agent-container'
    backendAzureRmKey: terraform.tfstate

- task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV4@4
  displayName: 'Terraform : validate'
  inputs:
    command: validate
    backendServiceArm: 'npstackro-1676009261708 (14f56a24-f129-441e-a95b-0df01d75c3a7)'
    backendAzureRmResourceGroupName: 'rg_agent'
    backendAzureRmStorageAccountName: storageaccountagentshub
    backendAzureRmContainerName: 'agent-container'
    backendAzureRmKey: terraform.tfstate

- task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV4@4
  displayName: 'Terraform : apply'
  inputs:
    command: apply
    environmentServiceNameAzureRM: 'npstackro-1676009261708 (14f56a24-f129-441e-a95b-0df01d75c3a7)'
    backendServiceArm: 'npstackro-1676009261708 (14f56a24-f129-441e-a95b-0df01d75c3a7)'
    backendAzureRmResourceGroupName: 'rg_agent'
    backendAzureRmStorageAccountName: storageaccountagentshub
    backendAzureRmContainerName: 'agent-container'
    backendAzureRmKey: terraform.tfstate

