---
- name: Install Prerequisites and Configure Azure DevOps Agent
  hosts: your_vm  # Replace 'your_vm' with the appropriate inventory group or IP address

  tasks:
    - name: Update apt packages
      become: true
      apt:
        update_cache: yes

    - name: Install required packages
      become: true
      apt:
        name:
          - terraform
          - docker.io
        state: present

    - name: Install Azure CLI
      become: true
      apt:
        name: azure-cli
        state: present

    - name: Download and install Azure DevOps agent
      become: true
      shell: |
        mkdir myagent && cd myagent
        wget -O vsts-agent-linux-x64-3.234.0.tar.gz https://vstsagentpackage.azureedge.net/agent/3.234.0/vsts-agent-linux-x64-3.234.0.tar.gz
        tar zxvf vsts-agent-linux-x64-3.234.0.tar.gz
      args:
        executable: /bin/bash

    - name: Configure Azure DevOps agent
      become: true
      shell: |
        sudo ./config.sh --unattended --url https://dev.azure.com/Shubham1708698304552/ --auth pat --token x4x4wzwy7w53ikj54ipzhbnmjjnfohcewotpag7zx27ugkgusqmq --pool Default --agent LinuxAgent01 --acceptTeeEula
        ./run.sh
      args:
        chdir: /myagent
        executable: /bin/bash
