---
- name: Install Prerequisites and Configure Azure DevOps Agent
  hosts: localhost

  tasks:
    - name: Update apt packages
      become: true
      apt:
        update_cache: yes

    - name: Install Python and Python dependencies
      become: true
      apt:
        name:
          - python3
          - python3-pip
          - virtualenv
          - python3-setuptools
        state: present

    - name: Upgrade Pip & Setup Python Env
      become: true
      shell: |
        sudo apt install python3.10-venv   
        python3 -m venv venv
        source venv/bin/activate
        python3 -m pip install --upgrade pip
      args:
        executable: /bin/bash

    - name: Install required packages
      become: true
      apt:
        name:
          - docker.io
          - docker-compose
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common
        state: present

    - name: Install Azure CLI
      become: true
      shell: |
        curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
      args:
        executable: /bin/bash

    - name: Install kubectl
      become: true
      shell: |
        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
      args:
        executable: /bin/bash

    - name: Install Docker Compose
      become: true
      shell: |
        sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
      args:
        executable: /bin/bash